WEB_FINAL PROJECT_YOURTIMETABLE/WEB_FINAL PROJECT_YOURTIMETABLE/Controllers/EventController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WEB_FINAL_PROJECT_YOURTIMETABLE.Models;

namespace WEB_FINAL_PROJECT_YOURTIMETABLE.Controllers
{
    public class EventController : Controller
    {
        private YOURTIMETABLEDbContext db = new YOURTIMETABLEDbContext();

        //
        // GET: /Event/

        public ActionResult Index()
        {
            var events = db.Events.Include(e => e.UserProfile);
            return View(events.ToList());
        }

        //
        // GET: /Event/Details/5

        public ActionResult Details(int id = 0)
        {
            Event myevent = db.Events.Find(id);
            if (myevent == null)
            {
                return HttpNotFound();
            }
            return View(myevent);
        }

        //
        // GET: /Event/Create

        public ActionResult Create()
        {
            ViewBag.UserProfileUserId = new SelectList(db.UserProfiles, "UserId", "UserName");
            return View();
        }

        //
        // POST: /Event/Create

        [HttpPost]
        public ActionResult Create(Event myevent)
        {
            if (ModelState.IsValid)
            {
                db.Events.Add(myevent);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.UserProfileUserId = new SelectList(db.UserProfiles, "UserId", "UserName", myevent.UserProfileUserId);
            return View(myevent);
        }

        //
        // GET: /Event/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Event myevent = db.Events.Find(id);
            if (myevent == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserProfileUserId = new SelectList(db.UserProfiles, "UserId", "UserName", myevent.UserProfileUserId);
            return View(myevent);
        }

        //
        // POST: /Event/Edit/5

        [HttpPost]
        public ActionResult Edit(Event myevent)
        {
            if (ModelState.IsValid)
            {
                db.Entry(myevent).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UserProfileUserId = new SelectList(db.UserProfiles, "UserId", "UserName", myevent.UserProfileUserId);
            return View(myevent);
        }

        //
        // GET: /Event/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Event myevent = db.Events.Find(id);
            if (myevent == null)
            {
                return HttpNotFound();
            }
            return View(myevent);
        }

        //
        // POST: /Event/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Event myevent = db.Events.Find(id);
            db.Events.Remove(myevent);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

WEB_FINAL PROJECT_YOURTIMETABLE/WEB_FINAL PROJECT_YOURTIMETABLE/Controllers/FriendController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WEB_FINAL_PROJECT_YOURTIMETABLE.Models;

namespace WEB_FINAL_PROJECT_YOURTIMETABLE.Controllers
{
    public class FriendController : Controller
    {
        private YOURTIMETABLEDbContext db = new YOURTIMETABLEDbContext();

        //
        // GET: /Friend/

        public ActionResult Index()
        {
            var friends = db.Friends.Include(f => f.UserProfile);
            return View(friends.ToList());
        }

        //
        // GET: /Friend/Details/5

        public ActionResult Details(int id = 0)
        {
            Friend friend = db.Friends.Find(id);
            if (friend == null)
            {
                return HttpNotFound();
            }
            return View(friend);
        }

        //
        // GET: /Friend/Create

        public ActionResult Create()
        {
            ViewBag.UserProfileUserId = new SelectList(db.UserProfiles, "UserId", "UserName");
            return View();
        }

        //
        // POST: /Friend/Create

        [HttpPost]
        public ActionResult Create(Friend friend)
        {
            if (ModelState.IsValid)
            {
                db.Friends.Add(friend);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.UserProfileUserId = new SelectList(db.UserProfiles, "UserId", "UserName", friend.UserProfileUserId);
            return View(friend);
        }

        //
        // GET: /Friend/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Friend friend = db.Friends.Find(id);
            if (friend == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserProfileUserId = new SelectList(db.UserProfiles, "UserId", "UserName", friend.UserProfileUserId);
            return View(friend);
        }

        //
        // POST: /Friend/Edit/5

        [HttpPost]
        public ActionResult Edit(Friend friend)
        {
            if (ModelState.IsValid)
            {
                db.Entry(friend).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UserProfileUserId = new SelectList(db.UserProfiles, "UserId", "UserName", friend.UserProfileUserId);
            return View(friend);
        }

        //
        // GET: /Friend/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Friend friend = db.Friends.Find(id);
            if (friend == null)
            {
                return HttpNotFound();
            }
            return View(friend);
        }

        //
        // POST: /Friend/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Friend friend = db.Friends.Find(id);
            db.Friends.Remove(friend);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

WEB_FINAL PROJECT_YOURTIMETABLE/WEB_FINAL PROJECT_YOURTIMETABLE/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WEB_FINAL_PROJECT_YOURTIMETABLE.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Message = "Modify this template to jump-start your ASP.NET MVC application.";

            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your app description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

WEB_FINAL PROJECT_YOURTIMETABLE/WEB_FINAL PROJECT_YOURTIMETABLE/Controllers/TimetableController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WEB_FINAL_PROJECT_YOURTIMETABLE.Models;

namespace WEB_FINAL_PROJECT_YOURTIMETABLE.Controllers
{
    public class TimetableController : Controller
    {
        private YOURTIMETABLEDbContext db = new YOURTIMETABLEDbContext();

        //
        // GET: /Timetable/

        public ActionResult Index()
        {
            var timetables = db.Timetables.Include(t => t.UserProfile);
            return View(timetables.ToList());
        }

        //
        // GET: /Timetable/Details/5

        public ActionResult Details(int id = 0)
        {
            Timetable timetable = db.Timetables.Find(id);
            if (timetable == null)
            {
                return HttpNotFound();
            }
            return View(timetable);
        }

        //
        // GET: /Timetable/Create

        public ActionResult Create()
        {
            ViewBag.UserProfileUserId = new SelectList(db.UserProfiles, "UserId", "UserName");
            return View();
        }

        //
        // POST: /Timetable/Create

        [HttpPost]
        public ActionResult Create(Timetable timetable)
        {
            if (ModelState.IsValid)
            {
                db.Timetables.Add(timetable);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.UserProfileUserId = new SelectList(db.UserProfiles, "UserId", "UserName", timetable.UserProfileUserId);
            return View(timetable);
        }

        //
        // GET: /Timetable/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Timetable timetable = db.Timetables.Find(id);
            if (timetable == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserProfileUserId = new SelectList(db.UserProfiles, "UserId", "UserName", timetable.UserProfileUserId);
            return View(timetable);
        }

        //
        // POST: /Timetable/Edit/5

        [HttpPost]
        public ActionResult Edit(Timetable timetable)
        {
            if (ModelState.IsValid)
            {
                db.Entry(timetable).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UserProfileUserId = new SelectList(db.UserProfiles, "UserId", "UserName", timetable.UserProfileUserId);
            return View(timetable);
        }

        //
        // GET: /Timetable/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Timetable timetable = db.Timetables.Find(id);
            if (timetable == null)
            {
                return HttpNotFound();
            }
            return View(timetable);
        }

        //
        // POST: /Timetable/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Timetable timetable = db.Timetables.Find(id);
            db.Timetables.Remove(timetable);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

WEB_FINAL PROJECT_YOURTIMETABLE/WEB_FINAL PROJECT_YOURTIMETABLE/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<article>
    <p>
        Use this area to provide additional information.
    </p>

    <p>
        Use this area to provide additional information.
    </p>

    <p>
        Use this area to provide additional information.
    </p>
</article>

<aside>
    <h3>Aside Title</h3>
    <p>
        Use this area to provide additional information.
    </p>
    <ul>
        <li>@Html.ActionLink("Home", "Index", "Home")</li>
        <li>@Html.ActionLink("About", "About", "Home")</li>
        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
    </ul>
</aside>

WEB_FINAL PROJECT_YOURTIMETABLE/WEB_FINAL PROJECT_YOURTIMETABLE/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<hgroup class="title">
    @*<h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>*@
    <h1><b>Chào mừng bạn đến với Yourtimetable</b></h1>
</hgroup>

<section class="giupdo">
   @* <header>
        <h3>Phone</h3>
    </header>
    <p>
        <span class="label">Main:</span>
        <span>425.555.0100</span>
    </p>
    <p>
        <span class="label">After Hours:</span>
        <span>425.555.0199</span>
    </p>*@
    Để bắt đầu quản lý thời gian của bạn, hãy làm theo những công việc sau:
    <li>Truy cập đến lịch biểu để tiến hành sắp xếp thời gian biểu trong 1 ngày của bạn     @Html.ActionLink("Lịch biểu", "Index", "Timetable")</li>
    <li>Truy cập vào sự kiện để ghi chú những sự kiện quan trọng bạn cần ghi nhớ    @Html.ActionLink("Sự kiện", "Index", "Event")</li>
    Hi vọng tiện ích này sẽ giúp bạn quản lý tốt thời gina của bạn hơn
</section>
@*<section class="contact">
    <header>
        <h3>Email</h3>
    </header>
    <p>
        <span class="label">Support:</span>
        <span><a href="mailto:Support@example.com">Support@example.com</a></span>
    </p>
    <p>
        <span class="label">Marketing:</span>
        <span><a href="mailto:Marketing@example.com">Marketing@example.com</a></span>
    </p>
    <p>
        <span class="label">General:</span>
        <span><a href="mailto:General@example.com">General@example.com</a></span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Address</h3>
    </header>
    <p>
        One Microsoft Way<br />
        Redmond, WA 98052-6399
    </p>
</section>*@

WEB_FINAL PROJECT_YOURTIMETABLE/WEB_FINAL PROJECT_YOURTIMETABLE/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
@section featured {
    @*<section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1>@ViewBag.Title.</h1>
                <h2>@ViewBag.Message</h2>
            </hgroup>
            <p>
                To learn more about ASP.NET MVC visit
                <a href="http://asp.net/mvc" title="ASP.NET MVC Website">http://asp.net/mvc</a>.
                The page features <mark>videos, tutorials, and samples</mark> to help you get the most from ASP.NET MVC.
                If you have any questions about ASP.NET MVC visit
                <a href="http://forums.asp.net/1146.aspx/1?MVC" title="ASP.NET MVC Forum">our forums</a>.
            </p>
        </div>
    </section>*@
     <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
               @* <h1>@ViewBag.Title.</h1>
                <h2>@ViewBag.Message</h2>*@
                <h2><h1>HÃY LÀM CHỦ THỜI GIAN CỦA BẠN</h1></h2>
            </hgroup>
            @*<p>
               Hãy làm chủ thời gian cảu bạn
            </p>*@
        </div>
    </section>
}
@*<h3>We suggest the following:</h3>
<ol class="round">
    <li class="one">
        <h5>Getting Started</h5>
        ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
        enables a clean separation of concerns and that gives you full control over markup
        for enjoyable, agile development. ASP.NET MVC includes many features that enable
        fast, TDD-friendly development for creating sophisticated applications that use
        the latest web standards.
        <a href="http://go.microsoft.com/fwlink/?LinkId=245151">Learn more…</a>
    </li>

    <li class="two">
        <h5>Add NuGet packages and jump-start your coding</h5>
        NuGet makes it easy to install and update free libraries and tools.
        <a href="http://go.microsoft.com/fwlink/?LinkId=245153">Learn more…</a>
    </li>

    <li class="three">
        <h5>Find Web Hosting</h5>
        You can easily find a web hosting company that offers the right mix of features
        and price for your applications.
        <a href="http://go.microsoft.com/fwlink/?LinkId=245157">Learn more…</a>
    </li>
</ol>*@

<h3>Danh hiệu hiện tại: Đồng hồ giấy </h3>
<h3>Điểm tích lũy: 20</h3>
<h5><i><u>@Html.ActionLink("Xem thành tích bạn bè của bạn","Index","Friend")</u></i></h5>
<h5><i><u>@Html.ActionLink("Bảng Xếp Hạng Top 10","About","Home")</u></i></h5>